export class LeaveProjectResponse {
  static response =
    [
      {
        "lieuLeaveCount": 34.0,
        "casualLeaveCount": 34.5,
        "annualLeaveCount": 34.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 34.0,
        "projectName": "CSH",
        "onSiteLeaveCount": 34.5,
        "maternityLeaveCount": 34.5
      },
      {
        "lieuLeaveCount": 19.5,
        "casualLeaveCount": 45.5,
        "annualLeaveCount": 16.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 19.5,
        "projectName": "RND",
        "onSiteLeaveCount": 16.0,
        "maternityLeaveCount": 45.5
      },
      {
        "lieuLeaveCount": 0.0,
        "casualLeaveCount": 0.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 0.0,
        "projectName": "MGMT",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 0.0
      },
      {
        "lieuLeaveCount": 4.5,
        "casualLeaveCount": 5.0,
        "annualLeaveCount": 11.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 4.5,
        "projectName": "CG",
        "onSiteLeaveCount": 11.0,
        "maternityLeaveCount": 5.0
      },
      {
        "lieuLeaveCount": 15.5,
        "casualLeaveCount": 30.0,
        "annualLeaveCount": 20.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 15.5,
        "projectName": "YAS",
        "onSiteLeaveCount": 20.5,
        "maternityLeaveCount": 30.0
      },
      {
        "lieuLeaveCount": 5.5,
        "casualLeaveCount": 21.0,
        "annualLeaveCount": 9.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 5.5,
        "projectName": "CC",
        "onSiteLeaveCount": 9.5,
        "maternityLeaveCount": 21.0
      },
      {
        "lieuLeaveCount": 105.0,
        "casualLeaveCount": 158.5,
        "annualLeaveCount": 108.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 105.0,
        "projectName": "DSN",
        "onSiteLeaveCount": 108.0,
        "maternityLeaveCount": 158.5
      },
      {
        "lieuLeaveCount": 117.0,
        "casualLeaveCount": 132.0,
        "annualLeaveCount": 102.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 117.0,
        "projectName": "FC",
        "onSiteLeaveCount": 102.5,
        "maternityLeaveCount": 132.0
      },
      {
        "lieuLeaveCount": 1.0,
        "casualLeaveCount": 6.0,
        "annualLeaveCount": 4.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 1.0,
        "projectName": "Admin",
        "onSiteLeaveCount": 4.0,
        "maternityLeaveCount": 6.0
      },
      {
        "lieuLeaveCount": 33.0,
        "casualLeaveCount": 29.5,
        "annualLeaveCount": 6.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 33.0,
        "projectName": "COS",
        "onSiteLeaveCount": 6.0,
        "maternityLeaveCount": 29.5
      },
      {
        "lieuLeaveCount": 14.0,
        "casualLeaveCount": 26.5,
        "annualLeaveCount": 32.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 14.0,
        "projectName": "KDM",
        "onSiteLeaveCount": 32.0,
        "maternityLeaveCount": 26.5
      },
      {
        "lieuLeaveCount": 17.5,
        "casualLeaveCount": 55.0,
        "annualLeaveCount": 30.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 17.5,
        "projectName": "VH",
        "onSiteLeaveCount": 30.0,
        "maternityLeaveCount": 55.0
      },
      {
        "lieuLeaveCount": 32.0,
        "casualLeaveCount": 21.0,
        "annualLeaveCount": 55.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 32.0,
        "projectName": "SURF",
        "onSiteLeaveCount": 55.0,
        "maternityLeaveCount": 21.0
      },
      {
        "lieuLeaveCount": 16.0,
        "casualLeaveCount": 49.0,
        "annualLeaveCount": 40.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 16.0,
        "projectName": "VDS",
        "onSiteLeaveCount": 40.0,
        "maternityLeaveCount": 49.0
      },
      {
        "lieuLeaveCount": 28.0,
        "casualLeaveCount": 33.0,
        "annualLeaveCount": 27.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 28.0,
        "projectName": "DEM",
        "onSiteLeaveCount": 27.0,
        "maternityLeaveCount": 33.0
      },
      {
        "lieuLeaveCount": 9.0,
        "casualLeaveCount": 30.5,
        "annualLeaveCount": 28.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 9.0,
        "projectName": "FZ",
        "onSiteLeaveCount": 28.0,
        "maternityLeaveCount": 30.5
      },
      {
        "lieuLeaveCount": 3.0,
        "casualLeaveCount": 26.0,
        "annualLeaveCount": 24.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 3.0,
        "projectName": "AiGrow",
        "onSiteLeaveCount": 24.5,
        "maternityLeaveCount": 26.0
      },
      {
        "lieuLeaveCount": 15.0,
        "casualLeaveCount": 25.5,
        "annualLeaveCount": 4.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 15.0,
        "projectName": "DMC",
        "onSiteLeaveCount": 4.0,
        "maternityLeaveCount": 25.5
      },
      {
        "lieuLeaveCount": 5.5,
        "casualLeaveCount": 12.0,
        "annualLeaveCount": 2.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 5.5,
        "projectName": "BOI",
        "onSiteLeaveCount": 2.0,
        "maternityLeaveCount": 12.0
      },
      {
        "lieuLeaveCount": 10.5,
        "casualLeaveCount": 15.0,
        "annualLeaveCount": 4.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 10.5,
        "projectName": "SWAT",
        "onSiteLeaveCount": 4.0,
        "maternityLeaveCount": 15.0
      },
      {
        "lieuLeaveCount": 2.0,
        "casualLeaveCount": 14.0,
        "annualLeaveCount": 2.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 2.0,
        "projectName": "chargeNET",
        "onSiteLeaveCount": 2.0,
        "maternityLeaveCount": 14.0
      },
      {
        "lieuLeaveCount": 50.0,
        "casualLeaveCount": 95.0,
        "annualLeaveCount": 112.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 50.0,
        "projectName": "TC",
        "onSiteLeaveCount": 112.0,
        "maternityLeaveCount": 95.0
      },
      {
        "lieuLeaveCount": 34.5,
        "casualLeaveCount": 35.0,
        "annualLeaveCount": 16.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 34.5,
        "projectName": "Tritium",
        "onSiteLeaveCount": 16.5,
        "maternityLeaveCount": 35.0
      },
      {
        "lieuLeaveCount": 5.0,
        "casualLeaveCount": 18.0,
        "annualLeaveCount": 4.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 5.0,
        "projectName": "FDM",
        "onSiteLeaveCount": 4.5,
        "maternityLeaveCount": 18.0
      },
      {
        "lieuLeaveCount": 5.0,
        "casualLeaveCount": 18.5,
        "annualLeaveCount": 23.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 5.0,
        "projectName": "VEGA",
        "onSiteLeaveCount": 23.0,
        "maternityLeaveCount": 18.5
      },
      {
        "lieuLeaveCount": 1.5,
        "casualLeaveCount": 13.0,
        "annualLeaveCount": 13.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 1.5,
        "projectName": "HR",
        "onSiteLeaveCount": 13.0,
        "maternityLeaveCount": 13.0
      },
      {
        "lieuLeaveCount": 18.0,
        "casualLeaveCount": 29.5,
        "annualLeaveCount": 3.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 18.0,
        "projectName": "ITD",
        "onSiteLeaveCount": 3.0,
        "maternityLeaveCount": 29.5
      },
      {
        "lieuLeaveCount": 14.5,
        "casualLeaveCount": 14.5,
        "annualLeaveCount": 14.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 14.5,
        "projectName": "CLAST",
        "onSiteLeaveCount": 14.0,
        "maternityLeaveCount": 14.5
      },
      {
        "lieuLeaveCount": 2.0,
        "casualLeaveCount": 1.5,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 2.0,
        "projectName": "Legal",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 1.5
      },
      {
        "lieuLeaveCount": 13.5,
        "casualLeaveCount": 19.0,
        "annualLeaveCount": 3.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 13.5,
        "projectName": "RS",
        "onSiteLeaveCount": 3.0,
        "maternityLeaveCount": 19.0
      },
      {
        "lieuLeaveCount": 1.5,
        "casualLeaveCount": 7.0,
        "annualLeaveCount": 5.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 1.5,
        "projectName": "CV",
        "onSiteLeaveCount": 5.0,
        "maternityLeaveCount": 7.0
      },
      {
        "lieuLeaveCount": 17.5,
        "casualLeaveCount": 26.0,
        "annualLeaveCount": 7.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 17.5,
        "projectName": "LIA",
        "onSiteLeaveCount": 7.0,
        "maternityLeaveCount": 26.0
      },
      {
        "lieuLeaveCount": 3.0,
        "casualLeaveCount": 6.5,
        "annualLeaveCount": 2.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 3.0,
        "projectName": "CT",
        "onSiteLeaveCount": 2.0,
        "maternityLeaveCount": 6.5
      },
      {
        "lieuLeaveCount": 0.0,
        "casualLeaveCount": 0.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 0.0,
        "projectName": "OPB",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 0.0
      },
      {
        "lieuLeaveCount": 3.5,
        "casualLeaveCount": 7.0,
        "annualLeaveCount": 6.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 3.5,
        "projectName": "Finance",
        "onSiteLeaveCount": 6.0,
        "maternityLeaveCount": 7.0
      },
      {
        "lieuLeaveCount": 8.0,
        "casualLeaveCount": 17.0,
        "annualLeaveCount": 8.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 8.0,
        "projectName": "DA",
        "onSiteLeaveCount": 8.5,
        "maternityLeaveCount": 17.0
      },
      {
        "lieuLeaveCount": 2.0,
        "casualLeaveCount": 10.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 2.0,
        "projectName": "MKT",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 10.0
      },
      {
        "lieuLeaveCount": 8.0,
        "casualLeaveCount": 17.5,
        "annualLeaveCount": 9.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 8.0,
        "projectName": "EK",
        "onSiteLeaveCount": 9.0,
        "maternityLeaveCount": 17.5
      },
      {
        "lieuLeaveCount": 0.5,
        "casualLeaveCount": 8.5,
        "annualLeaveCount": 2.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 0.5,
        "projectName": "Kriyo",
        "onSiteLeaveCount": 2.0,
        "maternityLeaveCount": 8.5
      },
      {
        "lieuLeaveCount": 11.5,
        "casualLeaveCount": 12.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 11.5,
        "projectName": "TT",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 12.0
      },
      {
        "lieuLeaveCount": 3.0,
        "casualLeaveCount": 2.5,
        "annualLeaveCount": 1.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 3.0,
        "projectName": "BUFF",
        "onSiteLeaveCount": 1.0,
        "maternityLeaveCount": 2.5
      },
      {
        "lieuLeaveCount": 0.0,
        "casualLeaveCount": 6.0,
        "annualLeaveCount": 2.5,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 0.0,
        "projectName": "CURM",
        "onSiteLeaveCount": 2.5,
        "maternityLeaveCount": 6.0
      },
      {
        "lieuLeaveCount": 0.0,
        "casualLeaveCount": 0.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 0.0,
        "projectName": "NPMS",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 0.0
      },
      {
        "lieuLeaveCount": 5.0,
        "casualLeaveCount": 7.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 5.0,
        "projectName": "RCCL",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 7.0
      },
      {
        "lieuLeaveCount": 0.0,
        "casualLeaveCount": 3.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 0.0,
        "projectName": "UX",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 3.0
      },
      {
        "lieuLeaveCount": 0.0,
        "casualLeaveCount": 0.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 0.0,
        "projectName": "TA",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 0.0
      },
      {
        "lieuLeaveCount": 0.0,
        "casualLeaveCount": 0.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 0.0,
        "projectName": "QBITS",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 0.0
      },
      {
        "lieuLeaveCount": 2.5,
        "casualLeaveCount": 6.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 2.5,
        "projectName": "Rest-API",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 6.0
      },
      {
        "lieuLeaveCount": 2.5,
        "casualLeaveCount": 0.0,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 2.5,
        "projectName": "Leave",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 0.0
      },
      {
        "lieuLeaveCount": 1.0,
        "casualLeaveCount": 2.5,
        "annualLeaveCount": 0.0,
        "officialLeaveCount": 0.0,
        "noPayLeaveCount": 0.0,
        "medicalLeaveCount": 1.0,
        "projectName": "RM",
        "onSiteLeaveCount": 0.0,
        "maternityLeaveCount": 2.5
      }
    ];

}
