export class Employee {
  constructor(
    public newEmployeeId: string,
    public newEmployeeEPFNumber: string,
    public newEmployeeDomainUname: string,
    public newEmployeeCompanyEmail: string,
    public newEmployeeCompany: string,
    public newEmployeeOffice: string,
    public newEmployeeDesignation: string,
    public newEmployeeUniversity: string,
    public newEmployeeJoinedDate: string,
    public newEmployeeConfirmationDate: string,
    public newEmployeeAddToTotal: string,
    public newEmployeeLoginType: string,
    public newEmployeeTitle: string,
    public newEmployeeInitials: string,
    public newEmployeeUsedname: string,
    public newEmployeeFirstName: string,
    public newEmployeeLastName: string,
    public newEmployeeFullname: string,
    public newEmployeeGender: string,
    public newEmployeeDob: string,
    public newEmployeeMaritalStatus: string,
    public newEmployeeReligion: string,
    public newEmployeeNationality: string,
    public newEmployeeNICNumb: string,
    public newEmployeeDlicenseNumb: string,
    public newEmployeeRace: string,
    public newEmployeePassportNumb: string,
    public newEmployeePassportExpDate: string,
    public newEmployeeMobile: string,
    public newEmployeeLand: string,
    public newEmployeePersonalEmail: string,
    public newEmployeeAddress: string,
    public newEmployeeProvince: string,
    public newEmployeeDistrict: string,
    public newEmployeeDistanceToWork: string,
    public newEmployeeResidentialAddress: string,
    public newEmployeeResidentialProvince: string,
    public newEmployeeResidentialDistrict: string,
    public newEmployeeResidentialDistanceToWork: string,
    public newEmployeeProjectName: string,
    public newEmployeeProjectStartDate: string,
    public  newEmployeeFoodPref: string, // foodPref attribute added
    public newEmployeeFaceRecImage: string,
    public newEmployeeCountry: string
  ) {
  }
}
